const universities = [
  {
    name: "Wrocław University of Science & Technology",
    short: "WUST",
    country: "Poland",
    filter: "poland",
    flag: "🇵🇱",
    program: "Applied Computer Science BSc",
    duration: "3.5 years",
    tuition: "~€4,100 / year",
    acceptance: "~65–70%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes — min. score 72",
    duolingoScore: 72,
    sat: "❌ Not required",
    deadline: "Rolling — closes ~July for Oct intake",
    termStart: "October",
    visa: "Easy",
    visaNote: "~90–96% approval · 15 working days · No interview · No medical test before arrival",
    gradeNote: "No formal grade cutoff for international BSc. C grade unlikely to be a dealbreaker. Strong motivation letter recommended.",
    highlight: "Best for Duolingo + Easy Visa",
    color: "#3b82f6",
    website: "https://pwr.edu.pl",
    tags: ["Cheapest Tuition", "Easiest Visa", "Duolingo Confirmed"]
  },
  {
    name: "Gdańsk University of Technology",
    short: "GUT",
    country: "Poland",
    filter: "poland",
    flag: "🇵🇱",
    program: "Data Engineering BSc",
    duration: "3.5 years",
    tuition: "~€4,600 / year",
    acceptance: "~65–75%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes (confirm min. score with admissions)",
    duolingoScore: 80,
    sat: "❌ Not required",
    deadline: "Typically May–July for Oct intake",
    termStart: "October",
    visa: "Easy",
    visaNote: "~90–96% approval · 15 working days · No interview needed",
    gradeNote: "No minimum grade formally stated. C grade should not be a dealbreaker. Polytechnic university — more forgiving than research universities.",
    highlight: "Affordable + Easy Visa",
    color: "#3b82f6",
    website: "https://pg.edu.pl",
    tags: ["Easy Visa", "Duolingo Accepted", "Affordable"]
  },
  {
    name: "University of Debrecen",
    short: "UNIDEB",
    country: "Hungary",
    filter: "hungary",
    flag: "🇭🇺",
    program: "Computer Science BSc",
    duration: "3 years",
    tuition: "~€6,400 / year",
    acceptance: "~70–80%",
    acceptanceLevel: "accessible",
    duolingo: "✅ Oral entrance exam accepted instead of any language test",
    duolingoScore: null,
    sat: "❌ Not required",
    deadline: "Rolling — closes ~June for Sept intake · Stipendium Hungaricum: Jan 15",
    termStart: "September",
    visa: "Moderate",
    visaNote: "Hungarian Embassy in Islamabad · 4–6 weeks processing · High success rate when documents complete",
    gradeNote: "Requires entrance exam in mathematics. Strong exam performance offsets the C grade significantly. Most forgiving for transcript issues.",
    highlight: "Most forgiving for C grade",
    color: "#10b981",
    website: "https://edu.unideb.hu",
    tags: ["Stipendium Hungaricum", "Entrance Exam Option", "C-Grade Friendly"]
  },
  {
    name: "Eötvös Loránd University",
    short: "ELTE",
    country: "Hungary",
    filter: "hungary",
    flag: "🇭🇺",
    program: "Computer Science BSc",
    duration: "3 years",
    tuition: "~€6,400 / year",
    acceptance: "~60–70%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Online English interview substitutes any formal test",
    duolingoScore: null,
    sat: "❌ Not required",
    deadline: "April 30, 2026 (for Sept 2026 intake)",
    termStart: "September 1",
    visa: "Moderate",
    visaNote: "Hungarian D-type visa · 4–6 weeks processing · Embassy in Islamabad",
    gradeNote: "Requires good grades especially in Mathematics. If C is not in Math/Physics, chances improve. Foundation Year available as safe pathway.",
    highlight: "Foundation Year available",
    color: "#10b981",
    website: "https://www.elte.hu",
    tags: ["Stipendium Hungaricum", "Foundation Year Option", "Interview-Based English"]
  },
  {
    name: "University of Szeged",
    short: "SZEGED",
    country: "Hungary",
    filter: "hungary",
    flag: "🇭🇺",
    program: "Computer Science BSc",
    duration: "3 years",
    tuition: "~€6,400 / year",
    acceptance: "~65–75%",
    acceptanceLevel: "moderate",
    duolingo: "⚠️ Not listed — contact directly. Skype interview available.",
    duolingoScore: null,
    sat: "❌ Not required",
    deadline: "Jan 5 – Jun 15, 2026 (for Sept intake)",
    termStart: "September",
    visa: "Moderate",
    visaNote: "Hungarian D-type visa · Similar to other Hungary universities · Stipendium Hungaricum eligible",
    gradeNote: "Skype interview is part of admission — strong interview can compensate for C grade. Motivation letter required.",
    highlight: "Interview-based admission",
    color: "#10b981",
    website: "https://u-szeged.hu",
    tags: ["Stipendium Hungaricum", "Skype Interview", "Affordable"]
  },
  {
    name: "Masaryk University",
    short: "MU BRNO",
    country: "Czech Republic",
    filter: "czech",
    flag: "🇨🇿",
    program: "Informatics / Computer Science BSc",
    duration: "3 years",
    tuition: "~€4,000–5,000 / year (English-taught)",
    acceptance: "~50–60%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes — score 115 (confirmed for MSc; BSc uses aptitude test TSP)",
    duolingoScore: 115,
    sat: "❌ Not required",
    deadline: "Nov 1, 2025 – Feb 28, 2026 (for 2026/27)",
    termStart: "September",
    visa: "Moderate",
    visaNote: "Czech D-type residence permit · 60 days processing · Apply 3–4 months before start · Embassy in Islamabad",
    gradeNote: "Focus is on TSP aptitude test, not just grades. Strong test score can offset C grade. Czech-taught BSc is free.",
    highlight: "Free Czech-taught option",
    color: "#8b5cf6",
    website: "https://www.fi.muni.cz",
    tags: ["Aptitude Test Based", "Affordable", "Free Czech Option"]
  },
  {
    name: "Charles University",
    short: "CUNI",
    country: "Czech Republic",
    filter: "czech",
    flag: "🇨🇿",
    program: "Computer Science BSc",
    duration: "3 years",
    tuition: "~€7,100 / year",
    acceptance: "~40–50%",
    acceptanceLevel: "competitive",
    duolingo: "✅ Yes — min. score 110",
    duolingoScore: 110,
    sat: "❌ Not required (but math aptitude required)",
    deadline: "April 30, 2026",
    termStart: "September 29, 2026",
    visa: "Moderate–Hard",
    visaNote: "Czech D-type permit · Up to 90 working days processing · Apply in winter round to allow visa time",
    gradeNote: "Most selective on the list. Overall FSc aggregate should be above 60–65%. C grade is a notable risk. Strong math aptitude required.",
    highlight: "Duolingo DET 110",
    color: "#8b5cf6",
    website: "https://www.mff.cuni.cz",
    tags: ["Duolingo 110", "Prestigious", "More Competitive"]
  },
  {
    name: "Constructor University",
    short: "CUB",
    country: "Germany",
    filter: "germany",
    flag: "🇩🇪",
    program: "Computer Science BSc",
    duration: "3 years",
    tuition: "~€20,000 / year (scholarships up to €10,000)",
    acceptance: "~40–50%",
    acceptanceLevel: "competitive",
    duolingo: "✅ Yes — min. score 90",
    duolingoScore: 90,
    sat: "❌ Not required",
    deadline: "Rolling — Jan–March for Sept intake (apply early)",
    termStart: "September",
    visa: "Moderate–Hard",
    visaNote: "German student visa · €11,904 blocked account required · 6–12 weeks processing · Embassy appointments can be scarce · University provides visa help",
    gradeNote: "Holistic, internationally focused admissions. A/A+ in 9–11th helps offset C in 12th. Strong personal statement is key.",
    highlight: "Merit scholarships available",
    color: "#f59e0b",
    website: "https://constructor.university",
    tags: ["Merit Scholarships", "Duolingo 90", "International Campus"]
  },
  {
    name: "Riga Technical University",
    short: "RTU",
    country: "Latvia",
    filter: "latvia",
    flag: "🇱🇻",
    program: "Computer Science / IT BSc",
    duration: "3–4 years",
    tuition: "~€2,600–3,500 / year",
    acceptance: "~70–80%",
    acceptanceLevel: "accessible",
    duolingo: "⚠️ Not confirmed — verify with RTU admissions. IELTS 5.5 / TOEFL 61 confirmed.",
    duolingoScore: null,
    sat: "❌ Not required",
    deadline: "Typically April–June for Sept intake",
    termStart: "September",
    visa: "Moderate",
    visaNote: "Latvian D-type Schengen residence permit · Financial proof required · Manageable for well-prepared applicants",
    gradeNote: "No minimum grade formally published. C grade unlikely to be a major barrier. Very affordable option.",
    highlight: "Cheapest option overall",
    color: "#ef4444",
    website: "https://www.rtu.lv",
    tags: ["Lowest Tuition", "Accessible", "Schengen Country"]
  }
];
