const universities = [

  // ── NORWAY ────────────────────────────────────────
  {
    name: "Norwegian Univ. of Science & Technology",
    short: "NTNU",
    country: "Norway",
    filter: "norway",
    flag: "🇳🇴",
    program: "Computer Science BSc",
    duration: "3 years",
    tuition: "FREE (no tuition for anyone — pay semester fee ~€60)",
    acceptance: "~50–60%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes — min. score 120",
    duolingoScore: 120,
    sat: "❌ Not required",
    deadline: "December 1, 2025 (international applicants via admissions.no)",
    termStart: "August",
    visa: "Moderate",
    visaNote: "Norwegian student residence permit · Apply via UDI (Utlendingsdirektoratet) · 4–8 weeks processing · Financial proof: ~NOK 128,887/year (~€11,000) · Manageable for Pakistanis",
    gradeNote: "Literally free tuition — just pay ~€60 semester fee. Cost of living in Trondheim is high (~€900–1,200/month). C in 12th assessed holistically. Strong overall profile needed.",
    highlight: "FREE tuition for everyone",
    color: "#ef4444",
    website: "https://www.ntnu.edu",
    tags: ["FREE Tuition", "Duolingo 120", "World Ranked"]
  },
  {
    name: "University of Oslo",
    short: "UiO",
    country: "Norway",
    filter: "norway",
    flag: "🇳🇴",
    program: "Informatics / Computer Science BSc",
    duration: "3 years",
    tuition: "FREE (semester fee ~€60 only)",
    acceptance: "~55–65%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes — min. score 120",
    duolingoScore: 120,
    sat: "❌ Not required",
    deadline: "December 1, 2025 (via admissions.no)",
    termStart: "August",
    visa: "Moderate",
    visaNote: "Norwegian student residence permit · UDI online application · 4–8 weeks · Financial proof required · Straightforward for well-prepared Pakistanis",
    gradeNote: "Free tuition is a huge advantage. Oslo has high living costs. Informatics BSc is broad — covers CS, programming, AI. C in 12th is a concern but not automatic rejection.",
    highlight: "FREE + capital city",
    color: "#ef4444",
    website: "https://www.uio.no",
    tags: ["FREE Tuition", "Duolingo 120", "Capital City"]
  },

  // ── FINLAND ───────────────────────────────────────
  {
    name: "University of Oulu",
    short: "UOULU",
    country: "Finland",
    filter: "finland",
    flag: "🇫🇮",
    program: "Computer Science & Engineering BSc",
    duration: "3 years",
    tuition: "~€10,000 / year (non-EU) — scholarships available",
    acceptance: "~55–65%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes — min. score 105",
    duolingoScore: 105,
    sat: "❌ Not required",
    deadline: "January 2026 (Finnish university application period opens Dec/Jan)",
    termStart: "September",
    visa: "Moderate",
    visaNote: "Finnish residence permit for studies · Finnish Immigration Service (Migri) · 4–8 weeks · Financial proof ~€6,720/year · Good approval rate for Pakistanis",
    gradeNote: "More accessible than Aalto or Helsinki. C in 12th less likely to block admission. Admission partly based on entrance exam/online test — good score compensates for grades.",
    highlight: "Most accessible Finnish uni",
    color: "#06b6d4",
    website: "https://www.oulu.fi",
    tags: ["Duolingo 105", "Entrance Exam Option", "Scholarship Available"]
  },
  {
    name: "LUT University",
    short: "LUT",
    country: "Finland",
    filter: "finland",
    flag: "🇫🇮",
    program: "Software Engineering BSc",
    duration: "3 years",
    tuition: "~€10,000 / year (non-EU) — 50% tuition waiver scholarships available",
    acceptance: "~55–65%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes — min. score 102",
    duolingoScore: 102,
    sat: "❌ Not required",
    deadline: "January 2026 (Finnish application period)",
    termStart: "September",
    visa: "Moderate",
    visaNote: "Finnish residence permit · Migri application online · 4–8 weeks · Lower cost of living than Helsinki · ~€700–900/month living costs",
    gradeNote: "Technology-focused university. Holistic admissions — entrance test performance matters. C in 12th not an outright block. 50% scholarship can cut tuition to ~€5,000/year.",
    highlight: "50% tuition scholarships",
    color: "#06b6d4",
    website: "https://www.lut.fi",
    tags: ["Duolingo 102", "50% Scholarship", "Software Engineering"]
  },

  // ── SPAIN ─────────────────────────────────────────
  {
    name: "IE University",
    short: "IE",
    country: "Spain",
    filter: "spain",
    flag: "🇪🇸",
    program: "Computer Science & Artificial Intelligence BSc",
    duration: "4 years",
    tuition: "~€21,000 / year (merit scholarships up to 60% available)",
    acceptance: "~45–55%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes — min. score 110",
    duolingoScore: 110,
    sat: "❌ Not required",
    deadline: "Rolling — apply early (Nov–Feb for best scholarship chances)",
    termStart: "September",
    visa: "Moderate",
    visaNote: "Spanish student visa (Type D) · 4–6 weeks processing · Embassy in Islamabad · Financial proof required · Manageable process",
    gradeNote: "Very internationally focused and holistic. Strong extracurriculars and motivation letter matter a lot. C in 12th can be offset by a strong interview and statement.",
    highlight: "Top private uni in Spain",
    color: "#f59e0b",
    website: "https://www.ie.edu",
    tags: ["Duolingo 110", "Merit Scholarships", "International Campus"]
  },
  {
    name: "Univ. Carlos III de Madrid",
    short: "UC3M",
    country: "Spain",
    filter: "spain",
    flag: "🇪🇸",
    program: "Computer Science & Engineering BSc (English-taught)",
    duration: "4 years",
    tuition: "~€5,000–7,000 / year (non-EU)",
    acceptance: "~50–60%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes — accepted for international applicants",
    duolingoScore: 100,
    sat: "❌ Not required",
    deadline: "March–June 2026 for Sept intake",
    termStart: "September",
    visa: "Moderate",
    visaNote: "Spanish student visa Type D · 4–6 weeks · Embassy in Islamabad · Less bureaucratic than German or Czech visa process",
    gradeNote: "Public university — much cheaper than IE. English-taught CS program is strong. FSc evaluated internationally. C in 12th is noted but public uni is more grade-lenient than private.",
    highlight: "Affordable public option",
    color: "#f59e0b",
    website: "https://www.uc3m.es",
    tags: ["Duolingo Accepted", "Affordable Public", "English-Taught"]
  },

  // ── SWITZERLAND ───────────────────────────────────
  {
    name: "USI — Università della Svizzera italiana",
    short: "USI",
    country: "Switzerland",
    filter: "swiss",
    flag: "🇨🇭",
    program: "Informatics BSc (Computer Science)",
    duration: "3 years",
    tuition: "~CHF 4,000 / year (~€4,200) — very affordable for Switzerland",
    acceptance: "~60–70%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes — min. score 105",
    duolingoScore: 105,
    sat: "❌ Not required",
    deadline: "April 30, 2026 for Sept intake",
    termStart: "September",
    visa: "Moderate",
    visaNote: "Swiss student residence permit · Apply via cantonal migration office · 4–8 weeks · Financial proof ~CHF 21,000/year · Swiss visa is well-structured and manageable",
    gradeNote: "Most affordable Swiss option. English-taught CS in Lugano (Italian-speaking Switzerland). C in 12th considered alongside overall profile. Strong CS faculty.",
    highlight: "Most affordable Swiss option",
    color: "#ef4444",
    website: "https://www.usi.ch",
    tags: ["Affordable for Switzerland", "Duolingo 105", "English-Taught"]
  },
  {
    name: "EPFL — École Polytechnique Fédérale",
    short: "EPFL",
    country: "Switzerland",
    filter: "swiss",
    flag: "🇨🇭",
    program: "Computer Science BSc",
    duration: "3 years",
    tuition: "~CHF 1,460 / year (~€1,500) — extremely low tuition",
    acceptance: "~30–40%",
    acceptanceLevel: "competitive",
    duolingo: "✅ Yes — accepted for international applicants",
    duolingoScore: 102,
    sat: "❌ Not required (but strong math background essential)",
    deadline: "January 15, 2026 for Sept intake",
    termStart: "September",
    visa: "Moderate",
    visaNote: "Swiss student residence permit · 4–8 weeks · Financial proof for living costs (~CHF 2,000/month) · Lausanne is expensive to live in but tuition is almost free",
    gradeNote: "One of the best CS universities in the world. Very competitive — strong math is mandatory. C in 12th is a significant risk. Worth a shot if Math/Physics grades are strong.",
    highlight: "World #1 CS — €1,500 tuition",
    color: "#ef4444",
    website: "https://www.epfl.ch",
    tags: ["Near-Free Tuition", "World Top 10 CS", "Very Competitive"]
  },

  // ── TURKEY ────────────────────────────────────────
  {
    name: "Middle East Technical University",
    short: "METU",
    country: "Turkey",
    filter: "turkey",
    flag: "🇹🇷",
    program: "Computer Engineering BSc",
    duration: "4 years",
    tuition: "~€700–1,500 / year",
    acceptance: "~35–45%",
    acceptanceLevel: "competitive",
    duolingo: "✅ Yes — min. score 105",
    duolingoScore: 105,
    sat: "❌ Not required",
    deadline: "April–May 2026 for Sept intake",
    termStart: "September",
    visa: "Easy",
    visaNote: "Turkish student visa · Simple process for Pakistanis · 2–3 weeks processing · Low rejection rate · Pakistani Embassy in Ankara handles fast",
    gradeNote: "Competitive but holistic. Strong 9–11th grades help offset the C in 12th. Worth applying — one of the best value CS programs in Europe.",
    highlight: "Best value in Europe",
    color: "#ef4444",
    website: "https://www.metu.edu.tr",
    tags: ["Incredibly Cheap", "Easy Visa", "Top CS Program"]
  },
  {
    name: "Bilkent University",
    short: "BILKENT",
    country: "Turkey",
    filter: "turkey",
    flag: "🇹🇷",
    program: "Computer Science BSc / Software Engineering BSc",
    duration: "4 years",
    tuition: "~€5,000–7,000 / year (scholarships available up to 100%)",
    acceptance: "~40–55%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes — min. score 110",
    duolingoScore: 110,
    sat: "❌ Not required",
    deadline: "May 2026 for Sept intake",
    termStart: "September",
    visa: "Easy",
    visaNote: "Turkish student visa · Very straightforward for Pakistanis · 2–3 weeks processing · University provides support",
    gradeNote: "Merit-based scholarships can reduce tuition significantly. A/A+ in earlier years strengthens scholarship application. C in 12th is noted but not an automatic disqualifier.",
    highlight: "Scholarships up to 100%",
    color: "#ef4444",
    website: "https://www.bilkent.edu.tr",
    tags: ["Merit Scholarships", "Easy Visa", "English-Taught"]
  },
  {
    name: "Koç University",
    short: "KOÇ",
    country: "Turkey",
    filter: "turkey",
    flag: "🇹🇷",
    program: "Computer Engineering BSc",
    duration: "4 years",
    tuition: "~€8,000 / year (50–100% scholarships available)",
    acceptance: "~40–50%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes — min. score 105",
    duolingoScore: 105,
    sat: "❌ Not required",
    deadline: "May 2026 for Sept intake",
    termStart: "September",
    visa: "Easy",
    visaNote: "Turkish student visa · Easy for Pakistanis · 2–3 weeks · Very high approval rate",
    gradeNote: "Strong scholarship program. Overall FSc aggregate matters more than individual year grades. Motivation letter can help explain C in 12th.",
    highlight: "Up to full scholarship",
    color: "#ef4444",
    website: "https://www.ku.edu.tr",
    tags: ["Full Scholarship Possible", "Easy Visa", "Prestigious"]
  },

  // ── SWEDEN ────────────────────────────────────────
  {
    name: "KTH Royal Institute of Technology",
    short: "KTH",
    country: "Sweden",
    filter: "sweden",
    flag: "🇸🇪",
    program: "Computer Science BSc / Software Engineering BSc",
    duration: "3 years",
    tuition: "~€19,000 / year (non-EU)",
    acceptance: "~30–40%",
    acceptanceLevel: "competitive",
    duolingo: "✅ Yes — min. score 110",
    duolingoScore: 110,
    sat: "❌ Not required",
    deadline: "January 15, 2026 (for Sept 2026 intake via universityadmissions.se)",
    termStart: "August / September",
    visa: "Moderate",
    visaNote: "Swedish residence permit for studies · Apply via Migrationsverket · 4–8 weeks processing · Financial proof: ~SEK 8,568/month · Straightforward for Pakistanis",
    gradeNote: "Selective — overall FSc aggregate evaluated. C in 12th is a risk for direct admission. Consider applying to BSc programs with lower competition alongside this.",
    highlight: "World top 100 CS",
    color: "#06b6d4",
    website: "https://www.kth.se",
    tags: ["World Ranked", "Duolingo 110", "Strong CS"]
  },
  {
    name: "Linköping University",
    short: "LIU",
    country: "Sweden",
    filter: "sweden",
    flag: "🇸🇪",
    program: "Computer Science BSc",
    duration: "3 years",
    tuition: "~€13,500 / year (non-EU)",
    acceptance: "~50–60%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes — min. score 105",
    duolingoScore: 105,
    sat: "❌ Not required",
    deadline: "January 15, 2026 (via universityadmissions.se)",
    termStart: "August",
    visa: "Moderate",
    visaNote: "Swedish residence permit · Same process as KTH · 4–8 weeks · Good approval rate for Pakistanis with complete documents",
    gradeNote: "Less selective than KTH. Overall grades considered. The C in 12th grade is a concern but not an outright block. Strong earlier grades help.",
    highlight: "More accessible than KTH",
    color: "#06b6d4",
    website: "https://liu.se",
    tags: ["Duolingo 105", "Good CS", "More Accessible"]
  },

  // ── NETHERLANDS ───────────────────────────────────
  {
    name: "Vrije Universiteit Amsterdam",
    short: "VU",
    country: "Netherlands",
    filter: "netherlands",
    flag: "🇳🇱",
    program: "Computer Science BSc",
    duration: "3 years",
    tuition: "~€11,200 / year (non-EU)",
    acceptance: "~55–65%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes — min. score 100",
    duolingoScore: 100,
    sat: "❌ Not required",
    deadline: "April 1, 2026 (for Sept 2026 intake)",
    termStart: "September",
    visa: "Moderate",
    visaNote: "Dutch MVV/residence permit · University applies on your behalf · 4–8 weeks · Proof of funds ~€11,400/year · Manageable for Pakistanis",
    gradeNote: "Selection based on motivation and prior grades. C in 12th is notable — a strong motivation letter is essential. Dutch unis appreciate honest explanation.",
    highlight: "Amsterdam location",
    color: "#f97316",
    website: "https://www.vu.nl",
    tags: ["Duolingo 100", "Amsterdam", "English-Taught"]
  },
  {
    name: "University of Amsterdam",
    short: "UvA",
    country: "Netherlands",
    filter: "netherlands",
    flag: "🇳🇱",
    program: "Computer Science BSc",
    duration: "3 years",
    tuition: "~€11,200 / year (non-EU)",
    acceptance: "~45–55%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes — min. score 100",
    duolingoScore: 100,
    sat: "❌ Not required",
    deadline: "April 1, 2026 (for Sept 2026 intake)",
    termStart: "September",
    visa: "Moderate",
    visaNote: "Dutch MVV/residence permit · UvA handles application on your behalf · 4–8 weeks processing · Financial proof required",
    gradeNote: "Selective intake. Overall FSc profile considered. C in 12th grade will need to be addressed in personal statement. Strong math background is important.",
    highlight: "Top Dutch university",
    color: "#f97316",
    website: "https://www.uva.nl",
    tags: ["Duolingo 100", "Prestigious", "Amsterdam"]
  },

  // ── IRELAND ───────────────────────────────────────
  {
    name: "Dublin City University",
    short: "DCU",
    country: "Ireland",
    filter: "ireland",
    flag: "🇮🇪",
    program: "Computer Science BSc",
    duration: "4 years",
    tuition: "~€13,500 / year (non-EU)",
    acceptance: "~55–65%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes — min. score 110",
    duolingoScore: 110,
    sat: "❌ Not required",
    deadline: "Ongoing — apply via CAO/direct by March 2026",
    termStart: "September",
    visa: "Moderate",
    visaNote: "Irish student visa (C or D) · 4–6 weeks processing · Pakistani students report good approval rates · Financial proof ~€7,000–10,000",
    gradeNote: "DCU is more accessible than Trinity. FSc considered as equivalent to Irish Leaving Cert. C in 12th is a concern but not automatic rejection.",
    highlight: "Tech industry hub",
    color: "#10b981",
    website: "https://www.dcu.ie",
    tags: ["Duolingo 110", "Tech Hub", "English Speaking"]
  },
  {
    name: "University College Dublin",
    short: "UCD",
    country: "Ireland",
    filter: "ireland",
    flag: "🇮🇪",
    program: "Computer Science BSc",
    duration: "4 years",
    tuition: "~€20,000 / year (non-EU)",
    acceptance: "~45–55%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes — min. score 110",
    duolingoScore: 110,
    sat: "❌ Not required",
    deadline: "March–April 2026 for Sept intake",
    termStart: "September",
    visa: "Moderate",
    visaNote: "Irish student visa · 4–6 weeks · Good approval rate for Pakistanis with strong financials",
    gradeNote: "Holistic admissions. C in 12th grade is a risk but strong earlier results help. Ireland has work permit opportunities post-graduation which adds value.",
    highlight: "Post-study work rights",
    color: "#10b981",
    website: "https://www.ucd.ie",
    tags: ["Duolingo 110", "Work Rights After", "Prestigious"]
  },

  // ── ITALY ─────────────────────────────────────────
  {
    name: "University of Bologna",
    short: "UNIBO",
    country: "Italy",
    filter: "italy",
    flag: "🇮🇹",
    program: "Computer Science BSc (English-taught)",
    duration: "3 years",
    tuition: "€0–3,000 / year (income-based — often free or very low)",
    acceptance: "~60–70%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes — min. score 105",
    duolingoScore: 105,
    sat: "❌ Not required",
    deadline: "March–April 2026 for Sept intake",
    termStart: "September",
    visa: "Moderate",
    visaNote: "Italian student visa (Type D) · 4–6 weeks · Pakistan embassy in Rome/Islamabad · Financial proof required · Manageable process",
    gradeNote: "Income-based tuition can make this nearly free. C in 12th grade is unlikely to block admission — Bologna evaluates holistically. One of the oldest universities in the world.",
    highlight: "Can be nearly free",
    color: "#8b5cf6",
    website: "https://www.unibo.it",
    tags: ["Lowest Tuition Possible", "Duolingo 105", "Historic University"]
  },
  {
    name: "Politecnico di Torino",
    short: "POLITO",
    country: "Italy",
    filter: "italy",
    flag: "🇮🇹",
    program: "Computer Engineering BSc (English-taught)",
    duration: "3 years",
    tuition: "~€3,000–4,000 / year (income-based, can be lower)",
    acceptance: "~50–60%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes — min. score 100",
    duolingoScore: 100,
    sat: "❌ Not required",
    deadline: "April 2026 for Sept intake",
    termStart: "September",
    visa: "Moderate",
    visaNote: "Italian student visa Type D · 4–6 weeks · Financial proof ~€6,000–8,000 · University provides visa guidance",
    gradeNote: "Strong engineering reputation. Requires an admission test (TOLC-I). Good performance on test can compensate for C in 12th grade.",
    highlight: "Admission test based",
    color: "#8b5cf6",
    website: "https://www.polito.it",
    tags: ["Duolingo 100", "Affordable", "Test-Based Entry"]
  },


  {
    name: "Wrocław University of Science & Technology",
    short: "WUST",
    country: "Poland",
    filter: "poland",
    flag: "🇵🇱",
    program: "Applied Computer Science BSc",
    duration: "3.5 years",
    tuition: "~€4,100 / year",
    acceptance: "~65–70%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes — min. score 72",
    duolingoScore: 72,
    sat: "❌ Not required",
    deadline: "Rolling — closes ~July for Oct intake",
    termStart: "October",
    visa: "Easy",
    visaNote: "~90–96% approval · 15 working days · No interview · No medical test before arrival",
    gradeNote: "No formal grade cutoff for international BSc. C grade unlikely to be a dealbreaker. Strong motivation letter recommended.",
    highlight: "Best for Duolingo + Easy Visa",
    color: "#3b82f6",
    website: "https://pwr.edu.pl",
    tags: ["Cheapest Tuition", "Easiest Visa", "Duolingo Confirmed"]
  },
  {
    name: "Gdańsk University of Technology",
    short: "GUT",
    country: "Poland",
    filter: "poland",
    flag: "🇵🇱",
    program: "Data Engineering BSc",
    duration: "3.5 years",
    tuition: "~€4,600 / year",
    acceptance: "~65–75%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes (confirm min. score with admissions)",
    duolingoScore: 80,
    sat: "❌ Not required",
    deadline: "Typically May–July for Oct intake",
    termStart: "October",
    visa: "Easy",
    visaNote: "~90–96% approval · 15 working days · No interview needed",
    gradeNote: "No minimum grade formally stated. C grade should not be a dealbreaker. Polytechnic university — more forgiving than research universities.",
    highlight: "Affordable + Easy Visa",
    color: "#3b82f6",
    website: "https://pg.edu.pl",
    tags: ["Easy Visa", "Duolingo Accepted", "Affordable"]
  },
  {
    name: "University of Debrecen",
    short: "UNIDEB",
    country: "Hungary",
    filter: "hungary",
    flag: "🇭🇺",
    program: "Computer Science BSc",
    duration: "3 years",
    tuition: "~€6,400 / year",
    acceptance: "~70–80%",
    acceptanceLevel: "accessible",
    duolingo: "✅ Oral entrance exam accepted instead of any language test",
    duolingoScore: null,
    sat: "❌ Not required",
    deadline: "Rolling — closes ~June for Sept intake · Stipendium Hungaricum: Jan 15",
    termStart: "September",
    visa: "Moderate",
    visaNote: "Hungarian Embassy in Islamabad · 4–6 weeks processing · High success rate when documents complete",
    gradeNote: "Requires entrance exam in mathematics. Strong exam performance offsets the C grade significantly. Most forgiving for transcript issues.",
    highlight: "Most forgiving for C grade",
    color: "#10b981",
    website: "https://edu.unideb.hu",
    tags: ["Stipendium Hungaricum", "Entrance Exam Option", "C-Grade Friendly"]
  },
  {
    name: "Eötvös Loránd University",
    short: "ELTE",
    country: "Hungary",
    filter: "hungary",
    flag: "🇭🇺",
    program: "Computer Science BSc",
    duration: "3 years",
    tuition: "~€6,400 / year",
    acceptance: "~60–70%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Online English interview substitutes any formal test",
    duolingoScore: null,
    sat: "❌ Not required",
    deadline: "April 30, 2026 (for Sept 2026 intake)",
    termStart: "September 1",
    visa: "Moderate",
    visaNote: "Hungarian D-type visa · 4–6 weeks processing · Embassy in Islamabad",
    gradeNote: "Requires good grades especially in Mathematics. If C is not in Math/Physics, chances improve. Foundation Year available as safe pathway.",
    highlight: "Foundation Year available",
    color: "#10b981",
    website: "https://www.elte.hu",
    tags: ["Stipendium Hungaricum", "Foundation Year Option", "Interview-Based English"]
  },
  {
    name: "University of Szeged",
    short: "SZEGED",
    country: "Hungary",
    filter: "hungary",
    flag: "🇭🇺",
    program: "Computer Science BSc",
    duration: "3 years",
    tuition: "~€6,400 / year",
    acceptance: "~65–75%",
    acceptanceLevel: "moderate",
    duolingo: "⚠️ Not listed — contact directly. Skype interview available.",
    duolingoScore: null,
    sat: "❌ Not required",
    deadline: "Jan 5 – Jun 15, 2026 (for Sept intake)",
    termStart: "September",
    visa: "Moderate",
    visaNote: "Hungarian D-type visa · Similar to other Hungary universities · Stipendium Hungaricum eligible",
    gradeNote: "Skype interview is part of admission — strong interview can compensate for C grade. Motivation letter required.",
    highlight: "Interview-based admission",
    color: "#10b981",
    website: "https://u-szeged.hu",
    tags: ["Stipendium Hungaricum", "Skype Interview", "Affordable"]
  },
  {
    name: "Masaryk University",
    short: "MU BRNO",
    country: "Czech Republic",
    filter: "czech",
    flag: "🇨🇿",
    program: "Informatics / Computer Science BSc",
    duration: "3 years",
    tuition: "~€4,000–5,000 / year (English-taught)",
    acceptance: "~50–60%",
    acceptanceLevel: "moderate",
    duolingo: "✅ Yes — score 115 (confirmed for MSc; BSc uses aptitude test TSP)",
    duolingoScore: 115,
    sat: "❌ Not required",
    deadline: "Nov 1, 2025 – Feb 28, 2026 (for 2026/27)",
    termStart: "September",
    visa: "Moderate",
    visaNote: "Czech D-type residence permit · 60 days processing · Apply 3–4 months before start · Embassy in Islamabad",
    gradeNote: "Focus is on TSP aptitude test, not just grades. Strong test score can offset C grade. Czech-taught BSc is free.",
    highlight: "Free Czech-taught option",
    color: "#8b5cf6",
    website: "https://www.fi.muni.cz",
    tags: ["Aptitude Test Based", "Affordable", "Free Czech Option"]
  },
  {
    name: "Charles University",
    short: "CUNI",
    country: "Czech Republic",
    filter: "czech",
    flag: "🇨🇿",
    program: "Computer Science BSc",
    duration: "3 years",
    tuition: "~€7,100 / year",
    acceptance: "~40–50%",
    acceptanceLevel: "competitive",
    duolingo: "✅ Yes — min. score 110",
    duolingoScore: 110,
    sat: "❌ Not required (but math aptitude required)",
    deadline: "April 30, 2026",
    termStart: "September 29, 2026",
    visa: "Moderate–Hard",
    visaNote: "Czech D-type permit · Up to 90 working days processing · Apply in winter round to allow visa time",
    gradeNote: "Most selective on the list. Overall FSc aggregate should be above 60–65%. C grade is a notable risk. Strong math aptitude required.",
    highlight: "Duolingo DET 110",
    color: "#8b5cf6",
    website: "https://www.mff.cuni.cz",
    tags: ["Duolingo 110", "Prestigious", "More Competitive"]
  },
  {
    name: "Constructor University",
    short: "CUB",
    country: "Germany",
    filter: "germany",
    flag: "🇩🇪",
    program: "Computer Science BSc",
    duration: "3 years",
    tuition: "~€20,000 / year (scholarships up to €10,000)",
    acceptance: "~40–50%",
    acceptanceLevel: "competitive",
    duolingo: "✅ Yes — min. score 90",
    duolingoScore: 90,
    sat: "❌ Not required",
    deadline: "Rolling — Jan–March for Sept intake (apply early)",
    termStart: "September",
    visa: "Moderate–Hard",
    visaNote: "German student visa · €11,904 blocked account required · 6–12 weeks processing · Embassy appointments can be scarce · University provides visa help",
    gradeNote: "Holistic, internationally focused admissions. A/A+ in 9–11th helps offset C in 12th. Strong personal statement is key.",
    highlight: "Merit scholarships available",
    color: "#f59e0b",
    website: "https://constructor.university",
    tags: ["Merit Scholarships", "Duolingo 90", "International Campus"]
  },
  {
    name: "Riga Technical University",
    short: "RTU",
    country: "Latvia",
    filter: "latvia",
    flag: "🇱🇻",
    program: "Computer Science / IT BSc",
    duration: "3–4 years",
    tuition: "~€2,600–3,500 / year",
    acceptance: "~70–80%",
    acceptanceLevel: "accessible",
    duolingo: "⚠️ Not confirmed — verify with RTU admissions. IELTS 5.5 / TOEFL 61 confirmed.",
    duolingoScore: null,
    sat: "❌ Not required",
    deadline: "Typically April–June for Sept intake",
    termStart: "September",
    visa: "Moderate",
    visaNote: "Latvian D-type Schengen residence permit · Financial proof required · Manageable for well-prepared applicants",
    gradeNote: "No minimum grade formally published. C grade unlikely to be a major barrier. Very affordable option.",
    highlight: "Cheapest option overall",
    color: "#ef4444",
    website: "https://www.rtu.lv",
    tags: ["Lowest Tuition", "Accessible", "Schengen Country"]
  }
];
